spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blooddata?characterEncoding=utf8
      username: root
      password:
      data-username:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

